name: Build QEMU g233-board

on:
  push:
    branches:
      - g233-board
  pull_request:
    branches:
      - g233-board
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build meson

      - name: Build QEMU
        run: |
          ./configure
          make -j$(nproc)

      - name: Package binary artifacts
        run: |
          VERSION=$(git describe --tags || echo "dev-$(date +'%Y%m%d-%H%M%S')")
          ARCHIVE_NAME="qemu-g233-board-${VERSION}"
          mkdir -p ${ARCHIVE_NAME}/bin
          cp -a build/qemu-system-* ${ARCHIVE_NAME}/bin/ || cp -a x86_64-softmmu/qemu-system-* ${ARCHIVE_NAME}/bin/
          tar -czf "${ARCHIVE_NAME}.tar.gz" ${ARCHIVE_NAME}

      - name: Upload artifacts (tar.gz)
        uses: actions/upload-artifact@v3
        with:
          name: qemu-g233-board-tar
          path: "*.tar.gz"
          retention-days: 7
          
